name: jogo_da_memoria
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter    
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
  
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/jogo_memoria/
    - assets/images/jogo_imitacao/
    - assets/images/jogo_imitacao/animais/
    - assets/images/jogo_imitacao/audios/
    

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
